const MAP_STYLE = {
  version: 8,
  sources: {
    ne2_shaded: {
      maxzoom: 6,
      tileSize: 256,
      tiles: [
        "https://tiles.openfreemap.org/natural_earth/ne2sr/{z}/{x}/{y}.png",
      ],
      type: "raster",
    },
    openmaptiles: {
      type: "vector",
      url: "https://tiles.openfreemap.org/planet",
    },
  },
  sprite: "https://tiles.openfreemap.org/sprites/ofm_f384/ofm",
  glyphs: "https://tiles.openfreemap.org/fonts/{fontstack}/{range}.pbf",
  layers: [
    {
      id: "background",
      type: "background",
      paint: {
        "background-color": "#f8f4f0",
      },
    },
    {
      id: "natural_earth",
      type: "raster",
      source: "ne2_shaded",
      maxzoom: 7,
      paint: {
        "raster-opacity": [
          "interpolate",
          ["exponential", 1.5],
          ["zoom"],
          0,
          0.6,
          6,
          0.1,
        ],
      },
    },
    {
      id: "park",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "park",
      paint: {
        "fill-color": "#d8e8c8",
        "fill-opacity": 0.7,
      },
    },
    {
      id: "landuse_residential",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "landuse",
      maxzoom: 12,
      filter: ["==", ["get", "class"], "residential"],
      paint: {
        "fill-color": "hsla(35,57%,88%,0.49)",
      },
    },
    {
      id: "landcover_wood",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "landcover",
      filter: ["==", ["get", "class"], "wood"],
      paint: {
        "fill-antialias": false,
        "fill-color": "hsla(98,61%,72%,0.7)",
        "fill-opacity": 0.4,
      },
    },
    {
      id: "landcover_grass",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "landcover",
      filter: ["==", ["get", "class"], "grass"],
      paint: {
        "fill-antialias": false,
        "fill-color": "rgba(176, 213, 154, 1)",
        "fill-opacity": 0.3,
      },
    },
    {
      id: "water",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "water",
      filter: ["!=", ["get", "brunnel"], "tunnel"],
      paint: {
        "fill-color": "rgb(158,189,255)",
      },
    },
    {
      id: "waterway_river",
      type: "line",
      source: "openmaptiles",
      "source-layer": "waterway",
      filter: [
        "all",
        ["==", ["get", "class"], "river"],
        ["!=", ["get", "brunnel"], "tunnel"],
      ],
      layout: {
        "line-cap": "round",
      },
      paint: {
        "line-color": "#a0c8f0",
        "line-width": [
          "interpolate",
          ["exponential", 1.2],
          ["zoom"],
          11,
          0.5,
          20,
          6,
        ],
      },
    },
    {
      id: "road_motorway",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      minzoom: 5,
      filter: [
        "all",
        ["match", ["get", "brunnel"], ["bridge", "tunnel"], false, true],
        ["==", ["get", "class"], "motorway"],
        ["!=", ["get", "ramp"], 1],
      ],
      layout: {
        "line-cap": "round",
        "line-join": "round",
      },
      paint: {
        "line-color": "#fc8",
        "line-width": [
          "interpolate",
          ["exponential", 1.2],
          ["zoom"],
          5,
          0,
          7,
          1,
          20,
          18,
        ],
      },
    },
    {
      id: "road_trunk_primary",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["match", ["get", "brunnel"], ["bridge", "tunnel"], false, true],
        ["match", ["get", "class"], ["primary", "trunk"], true, false],
      ],
      layout: {
        "line-join": "round",
      },
      paint: {
        "line-color": "#fea",
        "line-width": [
          "interpolate",
          ["exponential", 1.2],
          ["zoom"],
          5,
          0,
          7,
          1,
          20,
          18,
        ],
      },
    },
    {
      id: "road_secondary_tertiary",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["match", ["get", "brunnel"], ["bridge", "tunnel"], false, true],
        ["match", ["get", "class"], ["secondary", "tertiary"], true, false],
      ],
      layout: {
        "line-cap": "round",
        "line-join": "round",
      },
      paint: {
        "line-color": "#fea",
        "line-width": [
          "interpolate",
          ["exponential", 1.2],
          ["zoom"],
          6.5,
          0,
          8,
          0.5,
          20,
          13,
        ],
      },
    },
    {
      id: "road_minor",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        [
          "match",
          ["get", "geometry-type"],
          ["LineString", "MultiLineString"],
          true,
          false,
        ],
        ["match", ["get", "brunnel"], ["bridge", "tunnel"], false, true],
        ["match", ["get", "class"], ["minor"], true, false],
      ],
      layout: {
        "line-cap": "round",
        "line-join": "round",
      },
      paint: {
        "line-color": "#fff",
        "line-width": [
          "interpolate",
          ["exponential", 1.2],
          ["zoom"],
          13.5,
          0,
          14,
          2.5,
          20,
          18,
        ],
      },
    },
    {
      id: "building",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "building",
      minzoom: 13,
      maxzoom: 14,
      paint: {
        "fill-color": "hsl(35,8%,85%)",
      },
    },
    {
      id: "boundary_2",
      type: "line",
      source: "openmaptiles",
      "source-layer": "boundary",
      filter: [
        "all",
        ["==", ["get", "admin_level"], 2],
        ["!=", ["get", "maritime"], 1],
      ],
      layout: {
        "line-cap": "round",
        "line-join": "round",
      },
      paint: {
        "line-color": "hsl(248,1%,41%)",
        "line-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          3,
          1,
          5,
          1.2,
          12,
          3,
        ],
      },
    },
    {
      id: "label_city",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "place",
      minzoom: 3,
      filter: ["==", ["get", "class"], "city"],
      layout: {
        "text-field": ["coalesce", ["get", "name_en"], ["get", "name"]],
        "text-font": ["Noto Sans Regular"],
        "text-size": [
          "interpolate",
          ["exponential", 1.2],
          ["zoom"],
          4,
          11,
          7,
          13,
          11,
          18,
        ],
      },
      paint: {
        "text-color": "#000",
        "text-halo-blur": 1,
        "text-halo-color": "#fff",
        "text-halo-width": 1,
      },
    },
    {
      id: "label_country",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "place",
      maxzoom: 9,
      filter: ["==", ["get", "class"], "country"],
      layout: {
        "text-field": ["coalesce", ["get", "name_en"], ["get", "name"]],
        "text-font": ["Noto Sans Bold"],
        "text-size": ["interpolate", ["linear"], ["zoom"], 2, 9, 5, 17],
      },
      paint: {
        "text-color": "#000",
        "text-halo-blur": 1,
        "text-halo-color": "#fff",
        "text-halo-width": 1,
      },
    },
  ],
};
export default MAP_STYLE;
